create:
  handler: users/create.create
  events:
    - http:
        path: /users
        method: post
        private: true

list:
  handler: users/list.list
  events:
    - http:
        path: /users
        method: get
        private: true

get:
  handler: users/get.get
  events:
    - http:
        path: /users/{id}
        method: get
        private: true

update:
  handler: users/update.update
  events:
    - http:
        path: /users/{id}
        method: put
        private: true

delete:
  handler: users/delete.delete
  events:
    - http:
        path: /users/{id}
        method: delete
        private: true
